<a href="https://colab.research.google.com/github/Denixer/AN-LISIS-Y-VISUALIZACI-N-DE-DATOS/blob/main/consultas_medicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#cargar librerias
import pandas as pd
import numpy as np
import xlrd
import seaborn as sb
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter

# Cargar base de dato
from google.colab import files

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
df = pd.read_excel ("/content/drive/MyDrive/CONSULTAS_MEDICAS_2019_2023.xlsx")

In [ ]:
# comando para mostar los campos con su wwww de una tabla
df.dtypes

NameError: ignored

In [ ]:
df.head(5)

,AÑO,MES,ESPECIALIDAD,TOTAL,0_4,5_9,10 _14,15_19,20_24,25_29,...,operativos,GENERAL_MENOS_15,GENERAL_MAS15,CONTRA_MENOS15,CONTRA_MAS15,TOTAL_CONTRA,TOTAL_GENERAL,TOTAL_NUEVAS,TOTAL_NSP,TOTAL_ALTAS
0,2022,ENERO,PEDIATRÍA,100,42.0,25.0,28.0,5.0,0.0,0.0,...,NaN,50.0,4.0,NaN,NaN,0.0,54,52,51,8
1,2022,ENERO,MEDICINA INTERNA,42,0.0,0.0,0.0,1.0,1.0,1.0,...,19.0,0.0,5.0,NaN,NaN,0.0,5,12,19,0
2,2022,ENERO,NEONATOLOGÍA,59,59.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0,41,28,9
3,2022,ENERO,ENFERMEDAD RESPIRATORIA PEDIÁTRICA (BRONCOPULM...,96,41.0,23.0,27.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0,25,36,4
4,2022,ENERO,ENFERMEDAD RESPIRATORIA DE ADULTO (BRONCOPULMO...,112,0.0,0.0,2.0,5.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0,35,28,0